CREATE SEQUENCE PUBLIC.SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE plan (plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(256) NOT NULL);

CREATE TABLE task (task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, plan_id INTEGER, product_id INTEGER, target_quantity DOUBLE, status VARCHAR(100));

CREATE TABLE workorder (workorder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_quantity DOUBLE, actual_quantity DOUBLE, status VARCHAR(100));

CREATE TABLE inventory (inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(256), code VARCHAR(10), balance DOUBLE);

INSERT INTO inventory (name, code, balance) values ('Herbicide 1', 'HB1', '100');
INSERT INTO inventory (name, code, balance) values ('Herbicide 2', 'HB1', '200');
INSERT INTO inventory (name, code, balance) values ('Food 1', 'FD1', '500');
INSERT INTO inventory (name, code, balance) values ('Food 2', 'FD2', '600');
