package com.granular.dao;

import com.granular.model.Status;
import com.granular.model.WorkOrder;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class WorkOrderDaoTest {
   private Statement st;
   private Connection conn;

   @Before
   public void setUp() throws Exception {

      conn = DriverManager.getConnection("jdbc:hsqldb:mem:testdb", "sa", "");
      st = conn.createStatement();
      st.execute("CREATE TABLE workorder (workorder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_quantity DOUBLE, actual_quantity DOUBLE, status VARCHAR(100))");
   }

   @After
   public void tearDown() throws Exception {
      st.close();
      conn.close();
   }

   @Test
   public void testCRUDOperations() throws SQLException {

      WorkOrder workOrder1 = new WorkOrder();
      workOrder1.setActualQuantityApplied(50d);
      workOrder1.setWorkOrderStatus(Status.NOT_STARTED);
      workOrder1.setTargetQuantity(100d);

      WorkOrderDao dao = new WorkOrderDao(conn);
      dao.save(workOrder1);

      Iterable<WorkOrder> all = dao.findAll();

      List<WorkOrder> workOrders = new ArrayList<>();

      for (WorkOrder workOrder : all) {
         workOrders.add(workOrder);
      }

      assertEquals(1, workOrders.size());

   }
}
